version: "3"
services:
  influxdb:
    image: influxdb:alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - monitor
    volumes:
      - ./influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=test
      # - INFLUXDB_USER=lqm
      # - INFLUXDB_USER_PASSWORD=test123
      # - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=admin
  influxdbOld:
    image: influxdb:1.7
    container_name: influxdbOld
    ports:
      - "18086:8086"
    networks:
      - monitor
    volumes:
      - ./influxdb_dataOld:/var/lib/influxdb
      - ./influxdb_dataOld/conf/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_DB=test
  grafana:
    image: grafana/grafana:10.3.5
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - monitor
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitor:
